version: "3.8"
services:
  parallel_targets:
    image: code.chs.usgs.gov:5001/jross/parallelized_targets:latest
    build:
      context: .
    ports:
      - "8787:8787"
    environment:
      - ROOT=TRUE
      - PASSWORD=mypass

volumes:
  data:

